#image: maven:3.3-jdk-8
image: docker.cern.ch/c2mon-project/dind-java8-maven

#services:
# - docker.cern.ch/c2mon-project/dind
# - docker:latest

build:
  script: mvn -q -B -T4 clean deploy --settings settings.xml
