stages:
- build
- deploy
- sonar

# Get the settings file from c2mon project
before_script:
  - wget https://gitlab.cern.ch/c2mon/c2mon/raw/master/settings.xml

# Fully build and publish master branch
build_and_publish:
  stage: build
  script:
    - mvn -q -U -B clean deploy --settings settings.xml -Ddependencies.set.direct -X
  only:
    - master

# Just run tests on feature branches
build:
  stage: build
  script:
    - mvn -U -B clean test -DskipDockerBuild -DskipDockerTag --settings settings.xml -Ddependencies.set.direct
  except:
    - master

deploy_test:
  stage: deploy
  script:
    - version=`xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" ./pom.xml`; ssh timtest@timweb-test.cern.ch "~/scripts/deploy-web-ui-test.sh $version"
    - ssh timtest@timweb-test.cern.ch '/usr/opt/bin/wreboot -N C2MON-WEB-UI-TEST.jvm'
  environment:
    name: test
    url: https://timweb-test.cern.ch/c2mon-web-ui/
  only:
  - master

sonar_preview:
  type: sonar
  script:
    - mvn -q -U -B clean compile sonar:sonar -Dmaven.test.skip=true -Dsonar.host.url=https://en-ice-sonar.cern.ch -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.max_major_issues_gate=0 --settings settings.xml --debug -X
  except:
    - master

quality_assurance:
  stage: sonar
  script:
    - mvn package dependency-check:aggregate sonar:sonar -Dmaven.test.skip=true -Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml --settings settings.xml
  only:
    - master
